server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    # Archivos estáticos los sirve Nginx directamente
    # PHP no se involucra — más rápido
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Todo .php lo pasa a PHP-FPM
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloquea acceso a archivos ocultos (.env, .git)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
